# Generated by Django 4.2.6 on 2023-12-08 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_app', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='author',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='photo',
        ),
        migrations.DeleteModel(
            name='Revue',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
